spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kimyo_db
    username: kimyo_user
    password: root
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      uri: http://localhost:8888/
      label: main
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
  config:
    import: optional:configserver:http://localhost:8888/

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /order-service
  port: 8001